[package]
org = "osanda"
name = "inbounddelivery_scenario"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org="osa"
name="api_inbounddelivery_srv"
version="0.1.0"
repository="local"